#!/bin/sh

# ================= 配置区 =================
INTERFACES_FILE="/etc/network/interfaces"
RESOLV_FILE="/etc/resolv.conf"
BACKUP_DIR="/etc/network/backup_$(date +%Y%m%d%H%M%S)"

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[0;33m'
NC='\033[0m'

# ================= 环境检测 =================

# 1. 检查 Root
if [ "$(id -u)" -ne 0 ]; then
    echo -e "${RED}错误: 需要 root 权限${NC}"
    exit 1
fi

# 2. 自动检测网卡 (剔除 lo, sit, tun 等)
NIC=$(ip -o link show | awk -F': ' '{print $2}' | grep -vE "lo|sit|tun|docker" | head -n 1)
[ -z "$NIC" ] && NIC="eth0" # 兜底默认值

# 3. 读取当前 IP/网关 (用于输入框默认值)
CUR_IP=$(ip -4 addr show $NIC 2>/dev/null | grep -oP '(?<=inet\s)\d+(\.\d+){3}/\d+' | head -n 1)
CUR_GW=$(ip route show default 2>/dev/null | grep default | awk '{print $3}')
CUR_IP6=$(ip -6 addr show $NIC 2>/dev/null | grep -v "fe80" | grep -oP '(?<=inet6\s)[\da-f:]+/\d+' | head -n 1)

# 初始化变量
IPV4_MODE="dhcp"
IPV4_ADDR="$CUR_IP"
IPV4_GATE="$CUR_GW"

IPV6_MODE="auto"
IPV6_ADDR="$CUR_IP6"
IPV6_GATE=""

# ================= 辅助函数 =================

pause() {
    echo
    echo -e "${YELLOW}按回车继续...${NC}"
    read -r _
}

# 带有默认值的读取函数
# 用法: read_def "提示语" "变量名" "默认值"
read_def() {
    prompt="$1"
    var_name="$2"
    default_val="$3"
    
    if [ -n "$default_val" ]; then
        display_prompt="$prompt [默认: $default_val]: "
    else
        display_prompt="$prompt: "
    fi

    read -p "$display_prompt" input_val
    
    if [ -z "$input_val" ] && [ -n "$default_val" ]; then
        eval $var_name="$default_val"
    elif [ -n "$input_val" ]; then
        eval $var_name="$input_val"
    else
        # 输入为空且无默认值，循环
        eval $var_name=""
    fi
}

# ================= 功能模块 =================

config_v4() {
    clear
    echo -e "${CYAN}=== 配置 IPv4 ===${NC}"
    echo "1) DHCP (动态获取)"
    echo "2) Static (静态地址)"
    read -p "选择: " sel
    case "$sel" in
        1) IPV4_MODE="dhcp" ;;
        2) 
            IPV4_MODE="static"
            echo
            read_def "输入 IPv4 地址 (CIDR格式)" IPV4_ADDR "$CUR_IP"
            while [ -z "$IPV4_ADDR" ]; do
                read_def "地址不能为空，请重输" IPV4_ADDR ""
            done
            read_def "输入 IPv4 网关" IPV4_GATE "$CUR_GW"
            ;;
        *) echo "无效选择，保持默认" ;;
    esac
}

config_v6() {
    clear
    echo -e "${CYAN}=== 配置 IPv6 ===${NC}"
    echo "1) Auto (SLAAC 自动)"
    echo "2) Static (静态地址)"
    echo "3) Disable (禁用/手动)"
    read -p "选择: " sel
    case "$sel" in
        1) IPV6_MODE="auto" ;;
        2) 
            IPV6_MODE="static"
            echo
            read_def "输入 IPv6 地址 (CIDR格式)" IPV6_ADDR "$CUR_IP6"
            while [ -z "$IPV6_ADDR" ]; do
                 read_def "地址不能为空，请重输" IPV6_ADDR ""
            done
            read_def "输入 IPv6 网关 (可留空)" IPV6_GATE ""
            ;;
        3) IPV6_MODE="manual" ;;
        *) echo "无效选择" ;;
    esac
}

config_dns() {
    clear
    echo -e "${CYAN}=== 配置 DNS (/etc/resolv.conf) ===${NC}"
    echo -e "${YELLOW}注意: 如果使用 DHCP，重启后 DNS 可能会被重置。${NC}"
    echo "当前 DNS 内容:"
    cat $RESOLV_FILE
    echo "------------------------"
    echo "请输入 DNS 服务器 IP (空格分隔)，直接回车则不修改"
    read -p "DNS: " new_dns
    if [ -n "$new_dns" ]; then
        echo "# Generated by net script" > "$RESOLV_FILE"
        for d in $new_dns; do
            echo "nameserver $d" >> "$RESOLV_FILE"
        done
        echo -e "${GREEN}DNS 已写入${NC}"
    fi
}

apply_config() {
    clear
    echo -e "${CYAN}=== 准备应用配置 ===${NC}"
    
    # 生成预览
    TEMP_FILE="/tmp/interfaces.preview"
    cat > "$TEMP_FILE" <<EOF
auto lo
iface lo inet loopback

auto $NIC
EOF

    # 写入 IPv4
    if [ "$IPV4_MODE" = "dhcp" ]; then
        echo "iface $NIC inet dhcp" >> "$TEMP_FILE"
    else
        echo "iface $NIC inet static" >> "$TEMP_FILE"
        echo "	address $IPV4_ADDR" >> "$TEMP_FILE"
        echo "	gateway $IPV4_GATE" >> "$TEMP_FILE"
    fi

    # 写入 IPv6
    if [ "$IPV6_MODE" = "auto" ]; then
        echo "iface $NIC inet6 auto" >> "$TEMP_FILE"
    elif [ "$IPV6_MODE" = "static" ]; then
        echo "iface $NIC inet6 static" >> "$TEMP_FILE"
        echo "	address $IPV6_ADDR" >> "$TEMP_FILE"
        [ -n "$IPV6_GATE" ] && echo "	gateway $IPV6_GATE" >> "$TEMP_FILE"
    elif [ "$IPV6_MODE" = "manual" ]; then
        echo "iface $NIC inet6 manual" >> "$TEMP_FILE"
    fi

    # 展示预览
    echo -e "${YELLOW}即将写入以下内容到 $INTERFACES_FILE:${NC}"
    echo "----------------------------------------"
    cat "$TEMP_FILE"
    echo "----------------------------------------"
    
    # 警告
    if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
        echo -e "${RED}警告: 你正在使用 SSH 连接。${NC}"
        echo -e "${RED}如果 IP 配置错误，你将与容器失联！${NC}"
    fi

    read -p "确认写入并重启网络? (y/n): " confirm
    if [ "$confirm" = "y" ]; then
        # 备份
        mkdir -p "$BACKUP_DIR"
        cp "$INTERFACES_FILE" "$BACKUP_DIR/"
        
        # 覆盖
        mv "$TEMP_FILE" "$INTERFACES_FILE"
        
        echo -e "${GREEN}正在重启网络服务...${NC}"
        # 兼容性重启命令
        if rc-service networking restart; then
            echo -e "${GREEN}成功!${NC}"
        else
            echo -e "${RED}重启失败，请检查配置或控制台日志${NC}"
            # 尝试回滚提示
            echo "配置已备份至: $BACKUP_DIR"
        fi
    else
        echo "已取消。"
        rm "$TEMP_FILE"
    fi
}

# ================= 主菜单 =================

while :; do
    clear
    echo -e "${CYAN}=== Alpine LXC 网络配置工具 ===${NC}"
    echo -e "网卡: ${GREEN}$NIC${NC}"
    echo "---------------------------------"
    echo -e "IPv4 状态: [${YELLOW}$IPV4_MODE${NC}] ${IPV4_ADDR:-未设置}"
    echo -e "IPv6 状态: [${YELLOW}$IPV6_MODE${NC}] ${IPV6_ADDR:-未设置}"
    echo "---------------------------------"
    echo "1. 设置 IPv4"
    echo "2. 设置 IPv6"
    echo "3. 设置 DNS"
    echo "4. 查看当前网络信息"
    echo "5. [应用配置] 并重启网络"
    echo "0. 退出"
    echo "---------------------------------"
    read -p "请输入选项: " choice
    
    case "$choice" in
        1) config_v4 ;;
        2) config_v6 ;;
        3) config_dns; pause ;;
        4) ip a; echo; ip r; pause ;;
        5) apply_config; pause ;;
        0) exit 0 ;;
        *) echo "无效输入"; pause ;;
    esac
done
